<!DOCTYPE html> 
<html>
<head>
	<title>附近的公共自行车</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />  
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style type="text/css">
	body, html,#map {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
	</style>
	<?php Comm\Tpl::js('http://libs.useso.com/js/jquery/2.1.1/jquery.min.js', false) ?>
    <?php Comm\Tpl::js("http://api.map.baidu.com/api?type=quick&ak={$js_config['baidu_ak']}&v=1.0", false) ?>
</head>

<body>
<div id="map"></div>



<script type="text/javascript">
<?php
    $js_config['tpl_version'] = Comm\Tpl::version();
?>
var $CONF = <?= json_encode($js_config) ?>;
</script>
<?php Comm\Tpl::js('/static/js/map_near.js') ?>
</body>
</html>